name: Backend Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'query-anecdotes-main/**'
  pull_request:
    branches: [main]
    types: [opened, synchronize]
    paths:
      - 'query-anecdotes-main/**'

jobs:
  backend_pipeline:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: query-anecdotes-main
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Check style
        run: npm run lint
      - name: Build
        run: npm run build